version: '3.9'

networks:
  ds-jueri:
    name: ds-jueri
    driver: bridge

services:

  ds-nginx:
    build:
      context: ./.docker/
      dockerfile: Dockerfile
    container_name: ds-nginx
    hostname: ho-nginx
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    networks:
      - ds-jueri
